### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by Gideonnn** [SamVerschueren/gulp-cordova-build-ios#18]
I am using the Android and iOS version of this plugin. The Android version works perfectly, though the iOS version is not giving me any output. This is my gulpfile:

```
var gulp = require('gulp');
var android = require('gulp-cordova-build-android');
var create = require('gulp-cordova-create');
var del = require('del');
var ios = require('gulp-cordova-build-ios');
var plugin = require('gulp-cordova-plugin');
var shell = require('gulp-shell');

gulp.task('default', function() {});

gulp.task('clean.cordova', function() {
  return del(['.cordova']);
});

gulp.task('build.cordova', shell.task('ng build -prod --base-href "./"'));

gulp.task('build.cordova.android', ['clean.cordova', 'build.cordova'], function() {
  return gulp.src('dist')
    .pipe(create({ id: 'com.some.something', name: 'My App Name' }))
    .pipe(android())
    .pipe(gulp.dest('dist/android'));
});

gulp.task('build.cordova.ios', ['clean.cordova', 'build.cordova'], function() {
  return gulp.src('dist')
    .pipe(create({ id: 'com.some.something', name: 'My App Name' }))
    .pipe(ios())
    .pipe(gulp.dest('dist/ios'));
});
```

Is there any reason why I don't receive any output at all?

**Comment by SamVerschueren** [comment]
The thing is that the `build-ios` plugin is not outputting anything yet. After calling `ios()` you will have to manually open the project in xcode so you can release it. You can find the project somewhere in the `dist` directory. This plugin needs more refactoring and that is being tracked by #1. So if you have any ideas or wanting to help me out on it, feel free to do so.

**Comment by Gideonnn** [comment]
Hi Sam,

I just got back to this project and again ran into this problem. With the code above I get an empty directory named `ios` and can't locate the project somewhere else in the dist folder. Any tips?
