### ISSUE TITLE
Errors are not shown and gulp task is silently stopped

### ISSUE THREAD

**Issue by pellekrogholt** [SamVerschueren/gulp-cordova-build-ios#2]
I have a strongly modified .cordova/platform/ios with a test project and multiple Info.plist in the configuration so behind the scene `plugman` cant find the right `.plist` file (solved by reordering the xcode project file).

I have a simple grunt tasks

```
...
function buildIosTask() {
    return gulp.src('.cordova')
        .pipe(ios())
        .pipe(gulp.dest(buildDest));
}
...
gulp.task('build-ios', [], buildIosTask);
```

I do:

```
$ gulp build-ios
[10:23:26] Starting 'build-ios'
```

Expected:

A print out with the error (pardon me if my gulp is setup wrongly)

When I look into `gulp-cordova-build-ios/index.js` and place a `debugger` err has the value:

```
{ stack: undefined,
name: 'CordovaError',
message: 'could not find -Info.plist file, or config.xml file.' }
```

**Comment by SamVerschueren** [comment]
Hi @pellekrogholt 

Don't think something is wrong with your gulp task. I noticed the silently failing issue in other plugins as well. Can you try removing the last `gulp.dest` step and check if the plugin is still failing silently. It looks like the `gulp.dest` step prevents the other plugins from logging failure messages.

Sam

**Comment by pellekrogholt** [comment]
Hi @SamVerschueren 

I did remove the dest:

```
...
function buildIosTask() {
    return gulp.src('.cordova')
        .pipe(ios());
}
...
gulp.task('build-ios', [], buildIosTask);
```

and bingo out put looks as expected:

```
[11:10:41] Starting 'build-ios'...
[11:10:42] 'build-ios' errored after 1.43 s
[11:10:42] Error in plugin 'gulp-cordova-build-ios'
Message:
    could not find -Info.plist file, or config.xml file.
```

Gulp version:

```
$ gulp --version
[11:15:03] CLI version 3.9.0
[11:15:03] Local version 3.9.0
```

So its likely a gulp error right ?

**Comment by SamVerschueren** [comment]
Not 100% sure about this as I have seen errors with other plugins appearing correctly. Maybe I am not throwing the errors correctly? I have to investigate on this.

**Comment by pellekrogholt** [comment]
oki I dont really have any ideas for `Maybe I am not throwing the errors correctly?` here and _now_.

**Comment by pellekrogholt** [comment]
HI @SamVerschueren

another related thing: 
- am I on a completely wrong track with that dest dir used within `gulp-cordova-build-ios` ? 

I'm trying to achieve a similar thing - as you do with create android - where its possible to output an apk (https://github.com/SamVerschueren/gulp-cordova-build-android#usage).

a. i'm trying to output an ios Project.app to an dest folder that is not under `.cordova/platforms/ios`.

b. i'm confused what you do with ios that have been build and

```
  $ /path/to/my_new_project/cordova/build --release
```

let me know if I should move the above questions out side the issue ~ else where ?

thx

//

pelle

**Comment by SamVerschueren** [comment]
I am not quite sure I understand your question. You probably want to create `gulp-cordova-build-ios` to have the same functionality as `gulp-cordova-build-android`. Something I want as well but I am not very familiar with the iOS process.

The problem with iOS is that you need your entire project folder so you can generate an IPA file, right? Generating an IPA should be possible as you can read in issue https://github.com/SamVerschueren/gulp-cordova-build-ios/issues/1.

**Comment by pellekrogholt** [comment]
@SamVerschueren thx for taking the effort to try to understand my cramped up question.

Your answer helped especially  with #1 in context. I will try to take a deep look into it and if I find a fruitful solution make an PR. I just can not promise _when_ this will happen.

**Comment by SamVerschueren** [comment]
No problem, all help on this is welcome :). Will close this issue. Use #1 to post more information or to reference to later on.

**Comment by pellekrogholt** [comment]
+1
