### ISSUE TITLE
Allow defining the platform version

### ISSUE THREAD

**Issue by ankon** [SamVerschueren/gulp-cordova-build-ios#6]
Currently the plugin always uses `cordova platform add ios`, it would be great if one could define an optional version to trigger an invocation like this: `cordova platform add ios@VERSION`.

**Comment by ankon** [comment]
I'll be working on a PR for this (and a similar one for https://github.com/SamVerschueren/gulp-cordova-build-android)

**Comment by SamVerschueren** [comment]
:+1:
